from .Department import Department
from .Course import Course
from .Major import Major
from .Section import Section
from .Student import Student
from .Enrollment import Enrollment
from .StudentMajor import StudentMajor
from .LetterGrade import LetterGrade
from .PassFail import PassFail
